### ISSUE TITLE
Add all examples to CI

### ISSUE THREAD

**Issue by sehz** [infinyon/stateful-dataflows-examples#3]
in main, always last stable release.
in branch use dev release, this should be trigger by changes in the sdf repo or run each nightly.

**Comment by ajhunyady** [comment]
@morenol let me know when everything is in place and I can start testing.

**Comment by ajhunyady** [comment]
@sehz this issue is different from what I signed-up for. My task is to manually test `preview-9`.

**Comment by sehz** [comment]
Got it. I will create separate issue and move this this to preview 10
